layout_spectrum: 0.6358956671319902
typography_spectrum: 0.26014656969346106
color:
  brandStrength: 0.3519589623901993
  lightness: 0.6213497298303992
  saturation: 0.8189939216244966
  rhythmicContrast: 0.4702185543719679
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
name: litas
title: LITAS
